---
title: "¿Qué es la criminología?"
author:
  name: Juanjo Medina
  affiliation: Universidad de Sevilla
---

## Definiendo la criminología

Si estás leyendo estas líneas deberías tener una idea de cómo responder esta pregunta, pues este es un libro escrito para estudiantes de criminología a los que se les debe asumir un mínimo conocimiento sobre de qué va la titulación que han elegido. Pero esas ideas pueden estar contaminadas por relatos públicos que existen sobre la criminología que no se corresponden con la realidad.

Cuando, siendo más joven, iba a alguna fiesta y me preguntaban a qué me dedicaba, me costaba la misma vida decir que era criminólogo porque sabía cómo iba a acabar la conversación. Generalmente la cosa derivaba hacia las imágenes que el público tiene sobre los criminólogos y lo excitante que tiene que ser capturar a un delincuente. Hollywood, la industria del entretenimiento en general, tiene buena parte de la culpa de esos mitos que existen sobre la criminología. A veces en películas y series televisivas se introducen personajes que dicen ser criminólogos cuando en realidad son otra cosa. A veces eso se debe a un problema de traducción del inglés al español, otras veces es desconocimiento de los guionistas. No son criminólogos quienes se dedican a hacer perfiles sobre delincuentes en serie para ayudar a su captura, generalmente son psicólogas forenses. Tampoco son criminólogas quienes se dedican a recopilar y analizar pruebas que puedan servir a consolidar la evidencia probatoria en un juicio para condenar a alguien; suelen ser criminalistas, esto es personas con una carrera técnica (medicina, biología, informática, química, etc.) que pueden aportar sus conocimientos para estos fines y que suelen contar con algún tipo de formación especializada en policía científica. Las criminólogas son otra cosa.

¿Qué es, entonces, la criminología? Podría parecer una pregunta sencilla merecedora de una respuesta simple. Como veremos en realidad existen muchas formas de practicar y entender la criminología, que además han variado históricamente y entre distintos países, por lo que existen distintas formas de responder. No existe tampoco un consenso universal sobre las fronteras de la criminología (dónde empieza y dónde termina) y sobre cuál es su legítimo objeto de estudio. Veremos también que hay distintas formas de entender las relaciones de la criminología con otras disciplinas científicas y su carácter distintivo, así como con sus relaciones en el campo de la práctica profesional, las instituciones de la justicia penal y la administración pública, el activismo social, y el campo de la política.

El eminente criminólogo norteamericano Edwin Sutherland, autor de uno de los más influyentes manuales de criminología del siglo XX, definía la criminología como:

> “La criminología es el conjunto de conocimientos sobre el delito como fenómeno social. Incluye en su ámbito los procesos de elaboración de leyes, de infracción de leyes y de reacción ante la infracción de leyes. Estos procesos son tres aspectos de una secuencia de interacciones algo unificada. Ciertos actos que se consideran indeseables son definidos por las normas políticas. A pesar de esta limitación, algunas personas persisten en ese comportamiento y, por lo tanto, cometen delitos; la sociedad política reacciona con castigos u otros tratamientos, o con medidas preventivas. Esta secuencia de interacciones es el objeto de estudio de la criminología.” [@Sutherland_47, pp. 1].

En manuales españoles más modernos, como el de la profesora @Larrauri_20, se da a entender que la criminología es una ciencia social que obtiene sus conocimientos de la observación y análisis de la realidad de la delincuencia y del funcionamiento del sistema penal. Y de una forma parecida @Redondo_23 [p.] definen la criminología como aquella "ciencia que estudia los comportamientos delictivos y las reacciones sociales frente a ellos”. Ambas son formulaciones resumidas de lo propuesto por Edwin Sutherland. Por su parte, y con la elegancia y sofisticación que lo suele caracterizar, el escocés David Garland caracteriza a la criminología de la siguiente forma:

> “Interpreto la criminología como un género específico de discurso e investigación sobre el delito – un género que se desarrolló durante la modernidad y que puede ser distinguido de otras formas de hablar y pensar sobre la conducta criminal. Así, por ejemplo, la pretensión de la criminología de ser una empresa científica basada en el análisis empírico la separa de los discursos morales y jurídico legales, mientras que su atención hacia el delito la diferencia de otros géneros científico sociales, como la sociología de la desviación y el control, cuyo objeto de estudio es más amplio y no se encuentra definido por el Código Penal. Desde mediados del siglo XX, la criminología de forma creciente ha venido a estar marcada de otros discursos por los adornos de una identidad distintiva, con sus revistas, asociaciones profesionales, cátedras, e institutos de investigación” [@Garland_02, p. 8]

Lo primero que tenéis que entender es que no hay nada sagrado o escrito en piedra sobre estas definiciones. Como en muchas otras cuestiones en las ciencias sociales tendréis que juzgar por vosotras mismas lo convincentes que son los argumentos para mantener una postura u otra. El hecho de que haya distintas interpretaciones o respuestas implica que es una cuestión contestada, y que no podemos considerar del todo cerrada. No obstante, podéis ver que hay elementos comunes en estas caracterizaciones.

Dado que esta es una introducción a la materia no podemos simplemente dejaros con la idea de que “hay muchas formas de entender la criminología, vosotros veréis cuál elegís.” Vamos a daros una definición personal preliminar que utilizaremos en este manual y luego iremos destilando y justificando sus partes. La criminología, para nosotras, puede definirse como:

> un proyecto intelectual y académico que se ha ido institucionalizando de forma gradual, desigual, y creciente en distintos países como disciplina o campo de estudio con un desarrollo socialmente determinado entroncado en las ciencias sociales, e interconectado de forma radical con varias disciplinas que tiene como objeto de reflexión e investigación: el delito como evento, las personas que cometen delitos, las personas que sufren el delito, y las respuestas socioculturales, políticas, e institucionales al mismo que hace todo esto desde una perspectiva plural, aunque históricamente desarrollada por hombres occidentales y blancos (con los sesgos y puntos ciegos que ello implica) y que al tratar de estas cuestiones es un cuerpo de conocimientos y prácticas sociales con consecuencias en la vida de las personas y la sociedad que hace imposible no considerar su naturaleza política

### La criminología como proyecto intelectual y académico

Quizás hayáis notado que hablamos de la criminología como proyecto intelectual y académico, un término más amplio, en lugar de ciencia, como hacen la mayoría de otros manuales. Esto es algo que tiene que ver con debates que existen sobre cuál es la naturaleza legítima del conocimiento criminológico. La razón por la que preferimos esta terminología es porque creemos que es más generosa con las distintas formas de hacer criminología y más abierta a capturar y aceptar las distintas almas de la criminología.

Y es que en las ciencias sociales han coexistido, desde el siglo XIX, dos culturas, dos formas de entenderlas. Una tendencia ha sido acercarse a las humanidades, mientras que otra ha tendido más a un acercamiento a las ciencias naturales. Han coexistido, no de forma pacífica, una forma de conocer el mundo (lo que en términos técnicos se denomina epistemología) **idiográfica** - que ha destacado la particularidad de todo fenómeno social, la utilidad limitada de las generalizaciones, y la necesidad de la comprensión empática – con una forma de conocer el mundo **nomotética** -que ha destacado el paralelismo entre los procesos humanos y sociales con los procesos materiales y ha buscado el desarrollo de leyes universales que se puedan aplicar al mundo social.

Como destaca @Wallerstein_04 [p. 19] las ciencias sociales han sido como “alguien atado a dos caballos galopando en dirección contraria”. David Smith (2014) resume bien esta situación dentro de la criminología europea:

> “De un lado se encuentran quienes usan el lenguaje y los métodos de la ciencia, mientras que en el otro se encuentran quienes usan el lenguaje y los métodos de las humanidades. Hasta cierto grado, estas dos perspectivas están ligadas a distintas disciplinas académicas” (que contribuyen a la criminología) “pero en algunas instancias representan divisiones dentro de disciplinas establecidas. Así, en el campo de la ciencia están las contribuciones que proceden de la epidemiología, la genética, buena parte de la psiquiatría, la psicología social y experimental, casi toda la economía, y toda sociología que trabaja con estadísticas oficiales y encuestas. En el campo de las humanidades se encuentran buena parte de la sociología, historia, teoría política, la mayoría de los estudios sobre medios de comunicación, y la teoría psicoanalítica. Mientras que disciplinas como la antropología social se encuentran a medio camino. El campo de las ciencias tiene afinidad con la filosofía analítica, mientras que el campo de las humanidades tiene mayor afinidad con la filosofía continental. Hace 20 años el campo de las humanidades (no el de las ciencias) estaba muy influenciado por el marxismo o la teoría crítica, aunque estas influencias han disminuido… Este esquema es una simplificación muy cruda que exagera el contraste y hay autores que se sitúan entre ambos campos. No obstante, es importante tenerla en cuenta porque sirve como una guía útil para mapear la criminología, dado que se corresponde con diferentes métodos de investigación y concepciones de lo que es el conocimiento criminológico. Los que van de científicos usan números, estadísticas, encuestas y experimentos controlados, mientras que quienes se acercan a las humanidades describen eventos particulares y ejemplos singulares en toda su complejidad, insistiendo en matices y detalles (en contrapunto con la idea científica de “precisión”).” [@Smith_14, p.]

Pensamos, teniendo esto en cuenta, que definir la criminología como ciencia parece una forma de posicionarse frente a estas dos formas de entenderla. De hecho, cuando lees determinados autores y la forma en que definen la criminología como ciencia parece que esa es precisamente la intención. Parecería que es una forma de decir que solo el alma “cientificista” de la criminología que ha buscado acercarse al modelo de las ciencias naturales (y que en ocasiones puede representar los intereses del status quo) es la correcta o la adecuada. Creemos que adoptar esta postura es problemática a nivel normativo (es decir como objetivo a seguir) y a nivel descriptivo (de definir nuestro campo a día de hoy). A nivel normativo es empobrecedor: creemos que ambos enfoques, el cientificista y el que se aproxima a las humanidades tienen mucho que ofrecer para generar conocimiento enriquecedor. Y a nivel descriptivo no reflejaría bien la pluralidad de enfoques que coexisten dentro de la criminología como organización o fenómeno social. De ahí, que prefiramos esta terminología (proyecto intelectual y académico) como más inclusiva.

::: {.callout-note appearance="\"simple"}
**¿Es la criminología una profesión?**

Una consecuencia de definir la criminología como proyecto intelectual y académico es que no la estamos definiendo como una profesión. Este es otro debate (¿es la criminología una profesión?) que solo hemos visto planteado en España (aunque es posible que se de en otros países con un legado cultural como el nuestro) y que está relacionado con la manía que tenemos en nuestro país de encasillar y encorsetar (legal y administrativamente) todo, así como con el engranaje legal de nuestro mercado laboral. Ni en el mundo anglosajón ni en Europa central y del norte vamos a encontrar este tipo de debates. Sonaría a marciano. Sin entrar en debates sobre conceptos sociológicos y teóricos de lo que es una profesión, podemos preguntarnos si hay alguna ocupación laboral que solamente un graduado en criminología podría realizar. La respuesta, en nuestra opinión, es un no categórico y rotundo. Creemos que las titulaciones en criminología deberían capacitar a sus egresados para desarrollar un amplio espectro de ocupaciones laborales en el campo de la respuesta al delito, pero no creemos que esta capacitación los pone en una situación que les permita levantar murallas sobre determinadas ocupaciones que solamente ellos (los titulados o las tituladas en criminología) podrían o deberían realizar. En cuanto uno profundiza un poco sobre las habilidades, conocimientos y capacidades de cualquier ocupación laboral que los egresados en criminología quisieran monopolizar se vería que en realidad personas con otras titulaciones también desarrollan, o pueden desarrollar, dichas habilidades, conocimientos y capacidades de forma experta. No hay, por tanto, ninguna ocupación laboral que defina de forma específica al criminólogo. Aunque es verdad, al mismo tiempo, que su formación debería ponerles en una cierta ventaja competitiva o, cuanto menos facilitarles el acceso, en relación con distintas ocupaciones laborales en el ámbito de la seguridad, la prevención, y la intervención frente al delito tanto en el ámbito público como en el privado. En este sentido la persona con conocimientos criminológicos debería estar capacitada para:

-   desarrollar diagnósticos sobre el fenómeno criminal en un determinado marco espacio temporal;

-   evaluar y gestionar los riesgos y necesidades de intervención de víctimas y delincuentes;

-   desarrollar mapas de riesgo y vulnerabilidades en el sector público y privado;

-   diseñar, implementar y evaluar programas de detección y prevención de la delincuencia en contextos institucionales o comunitarios;

-   analizar, evaluar y desarrollar propuestas de políticas públicas en materia de delincuencia y seguridad.

Ocurre, no obstante, que en España funcionamos, por un lado, con una institución de origen feudal que son los colegios profesionales que aspiran a defender intereses corporativos creados y a monopolizar para los egresados en determinadas titulaciones ciertas ocupaciones. Y, por otro lado, contamos con una administración pública que a la hora de hacer convocatorias públicas y de definir sus plantillas laborales lo hace sobre esquemas generados en diálogo y negociación competitiva con estos colegios profesionales. Ocurre también que la criminología en España es una recién llegada en esta fiesta y los colegios profesionales ligados a otras titulaciones nos llevan ventaja y han levantado barreras para que los egresados en criminología puedan trabajar en determinados espacios de la administración pública. En ese sentido, aunque no creo que la criminología sea una profesión en el sentido aquí indicado, todo egresado en criminología interesado en la promoción profesional de su titulación debería luchar por la creación en su comunidad autónoma de un colegio profesional y colegiarse en dichos órganos para poder reivindicar de forma colectiva y más efectiva un mercado laboral más justo para quienes se especializan en este ámbito disciplinar. Pero sería un error de bulto que en los colegios profesionales empezáramos a pensar que hay que entrar al juego de levantar barreras.
:::

### La institucionalización de la criminología

Señalamos en nuestra propuesta que la criminología se ha ido institucionalizando de forma gradual, desigual, y creciente en distintos países como disciplina o campo de estudio. Entender que es la criminología puede ser más fácil si entendemos algo sobre su historia. Y también si clarificamos que es eso de una “disciplina”. Parafraseando al sociólogo Immanuel @Wallerstein_04 una disciplina es tres cosas de forma simultánea: categoría intelectual, estructura institucional, y cultura. Una disciplina:

> “es una categoría intelectual, una forma de afirmar que existe un campo determinado de estudio con algún tipo de fronteras (por más que sean disputadas, con otras disciplinas, o ambiguas) y con modos consensuados de hacer investigación de una forma legítima… Son construcciones sociales cuyos orígenes han de ser situados en las dinámicas del sistema histórico que les dan forma” [@Wallerstein_04, p. 166].

Es decir, son creaciones humanas definidas socialmente y que, para entender, como veremos también a continuación, hay que analizar también como objeto de análisis social e histórico (¿Por qué surgen cuando surgen? ¿Quién se beneficia de su aparición? ¿Por qué adoptan la forma que adoptan? ¿Cuáles son sus consecuencias sociales?).

> “Las disciplinas son también estructuras institucionales con formas más elaboradas desde finales del siglo XIX” [@Wallerstein_04, p. 166].

Estas estructuras y elementos que dotan de institucionalidad a la criminología son, por ejemplo, los departamentos universitarios, grados y otras titulaciones universitarias, revistas especializadas, sociedades científicas nacionales e internacionales, colecciones bibliográficas especializadas, premios ligados a la disciplina, congresos y convenciones periódicas, etc. Son el cemento que da concreción a la disciplina como categoría intelectual, “los adornos que dotan de identidad distintiva” a los que se refería David Garland en su definición.

> “Finalmente, las disciplinas son culturas. Los investigadores que se definen como miembros de una disciplina comparten algunas experiencias comunes. A menudo han leído los mismos libros ´clásicos´. Existen debates tradicionales bien conocidos dentro de cada disciplina y que son diferentes de los que existen en otras disciplinas. Cada disciplina favorece ciertas formas de hacer investigación sobre otras y recompensa a quienes usan los estilos apropiados. Y aunque la cultura puede cambiar, y de hecho cambia, con el paso del tiempo, en todo momento hay formas de presentación que es probable que sean más apreciadas por los miembros de una disciplina que de los de otra disciplina” [@Wallerstein_04, pp. 166-167].

La criminología ha adquirido los rasgos institucionales propios de una disciplina de forma relativamente reciente, sobre todo en España y en Europa. Uno de los vectores definitorios de la criminología en la actualidad es, sin duda, el notable crecimiento que ha experimentado en las últimas décadas.

::: {.callout-note appearance="\"simple"}
**Los titulaciones de criminología en España** 

La criminología como titulación universitaria reglada (como grado y máster oficial) son relativamente recientes. Fuera de nuestras fronteras, sobre todo en el mundo anglosajón, sí que había estudios universitarios oficiales sobre criminología desde hace varias décadas. Por ejemplo, la Escuela de Justicia Criminal de Rutgers University fue una de las primeras escuelas de criminología en Estados Unidos y fue fundada en 1974. En España la irrupción y expansión de estas titulaciones es posterior. Durante los 1990 se produce una proliferación de títulos propios (no reglados y homologados a nivel nacional) de criminología (“Expertos Universitarios”) ofrecidos desde Institutos de Criminología creados prácticamente todos ellos en el seno de Departamentos de Derecho Penal. Estos títulos de duración variable atrajeron un amplio número de matriculados y graduados, muchas veces procedentes del mundo de la policía o de la administración penitenciaria. Académicos vinculados a estos Institutos de Criminología -fundamentalmente penalistas, aunque en algunas universidades se consiguió atraer sobre todo a psicólogos- gestaron la Sociedad Española de Investigación Criminológica, y contribuyeron al llamado Libro Blanco de la Criminología. Este Libro Blanco proponía un plan de estudios consensuado, criticado por su falta de atención a las destrezas profesionales y el excesivo peso de asignaturas jurídicas [ver @Medina_02], que sirvió de base a la aprobación nacional de una titulación oficial a nivel nacional en criminología. Este reconocimiento finalmente llegó en el 2003, inicialmente como una licenciatura de segundo ciclo, y posteriormente con la aplicación del modelo Bolonia a los grados de 4 años que conocemos hoy. Desde entonces el número de grados de criminología se multiplicó de forma desmesurada y descontrolada para saciar una demanda estudiantil exagerada que estaba demasiado mediatizada por la construcción fantasiosa en la cultura popular de lo qué es un criminólogo y las nuevas sensibilidades culturales hacia el delito. La entrada en este mercado de las universidades a distancia y las universidades privadas contribuyeron aún más a magnificar de forma probablemente innecesaria, la oferta existente, para explotar esta demanda exagerada. A fecha de hoy, hay aproximadamente 20332 alumnos matriculados en grados de criminología (sin contar grados dobles) en nuestro país repartidos por las 41 universidades públicas y privadas que ofrecen estos títulos. Por contraponer un ejemplo que creo es relevante, tan solo hay 6345 alumnos matriculados en sociología repartidos en 16 universidades, todas públicas.

Por otro lado, en España todavía no hay departamentos universitarios de criminología. Por el contrario, la docencia en los grados de criminología se reparte entre departamentos diversos (derecho penal, sociología, psicología de la personalidad, etc.), aunque estas unidades organizativas, los departamentos de criminología, sí existen en universidades anglosajonas y europeas.
::: 

Pero la criminología como espacio de debate e investigación ha precedido a los grados de especialización en la misma. Así, por ejemplo, aunque no había grados específicos o departamentos universitarios, sí había asociaciones profesionales de científicos sociales especializados en el estudio de la criminología desde los años 1930. La *American Society of Criminology*, probablemente la más influyente a nivel internacional, se remonta a 1932 cuando varias personas ligadas al mundo de la policía comenzaron a reunirse de forma esporádica para debatir sobre cuestiones relacionadas con temas propios de la criminología, aunque no fue hasta 1946 que la palabra “criminología” aparecía en el nombre de este grupo (que a lo largo de los años ha ido creciendo y evolucionando de forma que veremos más adelante).

Muchas de estas asociaciones también han ido desarrollando sus propias revistas, como *Criminology* (fundada en 1963), la revista oficial de la Sociedad Americana de Criminología, o el *British Journal of Criminology* (fundada en 1960) la revista oficial de la *British Society of Criminology*.

Es importante destacar que, en todo caso, el pensamiento criminológico, la producción intelectual sobre cuestiones propias de la criminología, precede también a la creación de instituciones como las sociedades de criminólogos, sus revistas especializadas, sus departamentos universitarios, o las titulaciones universitarias en este ámbito - esto es, los distintos elementos institucionales que aspiran a dotar de una cierta autonomía organizativa. Hay quienes remontan los orígenes de este pensamiento al trabajo de autores como Jeremy Bentham (1748-1832) o Cesare Beccaria (1738-1794) durante el periodo de la Ilustración en el siglo XVIII. En este sentido, y con independencia de los adornos institucionales, la criminología como ciencia distintiva o discurso académico apenas tiene 150 años.

### La criminología como un producto socialmente determinado

Tenemos que entender que las disciplinas, en su triple dimensión (como categorías intelectuales, estructuras institucionales y organización social, y como cultura) son productos históricos y creaciones humanas con todas las consecuencias que ello tiene.

No nos debe caber duda que entender e interpretar la criminología y sus productos nos obliga a entender el contexto en el que opera. Como señalan @Loader_12 [p.7], parafraseando a Stanley Cohen:

> “El conocimiento sobre el delito y la justicia no surge de la nada. Ni está simplemente ubicada en las cabezas y las actividades de quienes lo producen. La cuestión de qué es lo que viene a conocerse, desde qué perspectivas teóricas, con qué métodos, sobre qué delitos, y formas de responder a la delincuencia, y con qué efectos está condicionado por un amplio rango de instituciones. Estas instituciones emplean al personal investigador (de forma permanente o temporal); financian (o no financian) proyectos y programas de investigación; permiten (o rechazan) al acceso a datos, sujetos o contextos de investigación; ofrecen espacios en los que publicar; y usan, abusan, se convierten en ardientes defensores, o ignoran los productos de esta investigación. Cada una de estas instituciones – universidades, organismos públicos y privados de financiación de estudios científicos, think tanks, firmas de consultoría, editoriales, periódicos y otros medios de comunicación social, grupos sociales organizados y empresas de lobbying, partidos políticos, prisiones, fuerzas policiales, ministerios, etc. – se encuentran a su vez situados en contextos sociales, políticos y económicos que condicionan cómo pueden pensar y operar. Estudiar la criminología como un “campo” implica estudiar cómo las relaciones y luchas de poder entre los actores en estos distintos espacios estructuran el conocimiento que se produce (y aquel que no se produce)”

Las disciplinas no son productos naturales que obedezcan a una ley inmutable que dice que tienen que existir o hacerlo en una forma concreta. O como señala Garland_02, la historia de las ideas en criminología no puede ser tratada como el desvelo gradual de una ciencia que siempre estaba destinada a aparecer. La criminología, por el contrario, es una organización de conocimientos y procedimientos de investigación que han sido construidos socialmente y responden a una específica configuración histórica, está asentada sobre una serie particular de instituciones y formas de vida que han dado lugar a su desarrollo.

Existe un interés cada vez más focalizado en tratar de entender la historia y el análisis sociológico de la criminología como disciplina. @Garland_02 ha propuesto que la criminología surgió de la confluencia de dos proyectos básicos – lo que él denomina el **proyecto Lombrosiano** y **el proyecto gubernamental**. Para Garland, solo podemos entender la criminología en su desarrollo histórico y en su constitución actual, si aceptamos que, por un lado, tiene un objetivo científico y surge de un proyecto científico orientado a entender la delincuencia, pero, por otro lado, tiene también un objetivo institucional orientado hacia la gobernanza administrativa de la delincuencia:

> “La única unidad, por frágil que sea, de la disciplina emerge de la creencia de que estos dos proyectos se apoyan el uno al otro, que no son incompatibles entre sí, que la investigación etiológica puede ser útil para propósitos administrativos y que los resultados de la investigación operativa puede servir a las pesquisas teóricas”.

Es posible interpretar esta propuesta en el sentido de reconocer que la criminología tiene objetos diversos de estudio, el delito y su control. Pero la idea de Garland va más allá, esto es, que la criminología como campo de estudio está íntimamente ligada a los esfuerzos estatales para controlar el delito. La aparición de las titulaciones de criminología en Estados Unidos, por ejemplo, está íntimamente ligada a las recomendaciones de comités presidenciales sobre la necesidad de mejorar la educación y la formación de los profesionales de la justicia penal y la dominación científica norteamericana está ligada a la muy notable dotación de fondos de investigación de las autoridades norteamericanas para financiar estudios capaces de mejorar la respuesta estatal al delito. Este vínculo entre las necesidades de control del Estado y el desarrollo de la criminología como disciplina hace que sea vital reconocer la naturaleza política de esta disciplina. En ese sentido es un lugar común señalar que una de las razones por las que hemos experimentado un mayor grado de institucionalización de la disciplina en Europa y en los países anglosajones es porque “los objetos propios de la investigación criminológica – el delito, la función policial, la justicia, el castigo, el miedo, las víctimas, control, orden, seguridad – desde los años 1980 han venido a ocupar un lugar más prominente y destacado en las vidas y conciencia de los ciudadanos y en el habla y las acciones de las autoridades gubernativas” @Loader_12 [p. 4].

@Garland_02b ha defendido que mientras que durante los primeros dos tercios del siglo XX vivíamos en un modelo político y cultural dominado por las ideas ligadas al concepto y las políticas del Estado del Bienestar Social, a partir de los años 80 transitamos a lo que él ha denominado como la cultura del control, en la que las cuestiones sobre inseguridad y delincuencia han venido a ser más prominentes y esto, por un lado, genera condiciones que son más propicias para el desarrollo de la criminología, pero también plantea retos para su desarrollo. Esta nueva cultura del control va ligada a una serie de desarrollos fundamentales en la gobernanza del delito que incluyen entre otros la politización de la cuestión criminal; el desarrollo de nuevas ansiedades ciudadanas frente al delito y el inmigrante explotados e incitados por los medios de comunicación; la expansión del castigo penal y otros mecanismos de control legales; la irrupción de nuevos actores (a menudo privados) en la gestión de la inseguridad; la creciente relevancia de nuevas tecnologías de control (inteligencia artificial, videovigilancia, etc.); el surgimiento de movimientos organizados de víctimas y su instrumentalización política; la globalización y la impronta que ha dejado en el flujo de ideas (generalmente unidireccional) sobre control del delito y en la aparición de nuevos retos de tipo criminal; etc. Podríamos detenernos en la forma en que cada una de estas transformaciones afecta a la criminología, aunque nos llevaría más espacio del que sería deseable.

Centrémonos en tan solo una de ellas: la politización del delito. El delito y la inseguridad ciudadana ya no son cuestiones gestionadas de forma tecnocrática por una serie de funcionarios al margen de la mirada del público. En la actualidad, las discusiones sobre la forma apropiada de responder al delito han pasado a ocupar un papel más prominente en el debate público y los partidos políticos compiten entre sí de forma más abierta en materia de política criminal, a menudo priorizando respuestas a corto plazo y tendentes a maximizar el rédito electoral (aunque no sean las respuestas más justas, eficaces, y humanas) en un contexto en el que los medios de comunicación social estimulan ansiedades públicas hacia el delito y respuestas emocionales, simplistas, y superficiales a problemas complejos. Como señalan @Loader_12  [p. 12]: “El resultado es un contexto político que es hiperactivo, volátil, inestable, y en el que resulta más difícil que la razón y la evidencia conduzcan lo que se dice y hace”. Una disciplina, como la criminología, que aspira precisamente a que la razón y la evidencia sean vectores importantes en las discusiones sobre el delito y su control, por tanto, se encuentran con una pendiente muy empinada que escalar en este contexto[^1]. 

### La naturaleza interdisciplinaria de la criminología

La criminología se encuentra fuertemente enraizada en las ciencias sociales, e interconectada de forma radical con varias disciplinas ¿Si no había grados en criminología hasta el último cuarto del siglo XX o sociedades científicas de criminólogos hasta mediados de dicho siglo como podía haber criminología? ¿Quién hacía criminología? La respuesta a estas preguntas nos puede ayudar a entender la naturaleza de la criminología. Y esa respuesta es que había académicos y científicos de procedencia muy diversa y plural pensando, reflexionando, e investigando sobre los objetos propios de la criminología mucho antes de que la criminología existiera como titulación o disciplina reconocida, antes de que empezara a adquirir grados de institucionalización propia y autónoma.

La criminología siempre ha sido una especialidad ecléctica y multidisciplinaria. El citado Cesare Beccaria, por ejemplo, era “literato, filósofo, jurista y economista” nos dice Wikipedia. Mientras que Edwin Sutherland, uno de los padres indiscutibles de la criminología moderna y con cuya definición de la criminología empezábamos este capítulo, era en realidad sociólogo.

En los planes de estudio de criminología y en vuestras lecturas de trabajos que versan sobre las cuestiones que interesan a los criminólogos veréis que convergen distintas disciplinas: sociología, psicología, ciencia política, economía, derecho, antropología, historia, y un largo etcétera. Cuando os adentréis en vuestros estudios de teoría criminológica podréis ver que a lo largo de la historia de la criminología la disciplina más influyente ha ido cambiando.

Esta pluralidad, no solamente sigue existiendo, sino que muchos pensamos que debe ser cultivada y es enormemente beneficiosa para la criminología, pero también genera dudas y debates sobre la naturaleza de la criminología. Sigue habiendo una contribución muy notable a la criminología realizada desde otras disciplinas como la psicología, la sociología, la ciencia política, la economía, y muchas otras disciplinas sociales y humanísticas hoy en día. Profesores, profesionales, e investigadores con este bagaje (sin un grado o doctorado en criminología) siguen generando reflexiones e investigaciones que son esenciales al desarrollo científico de la criminología y en el ámbito comparado trabajan a menudo como profesores de criminología en los departamentos universitarios de criminología.

No es exagerado señalar que los saltos cualitativos que se han ido produciendo en la criminología durante los últimos 150 años, la historia de la teoría criminológica, ha sido determinada por la suma al proyecto criminológico de nuevas comunidades de científicos sociales. La diferencia es que hoy en muchos países además contamos con académicos y científicos que hacen criminología, trabajan en departamentos de criminología, y algunos de ellos tienen grados específicos en criminología.

Pensar, por tanto, que es necesario haber estudiado formalmente un grado en criminología para poder contribuir a la producción criminológica es ignorar la historia y la realidad plural contemporánea de esta área de conocimiento. En ese sentido, para mí, un criminólogo o criminóloga es *cualquier científico social que se ha especializado a lo largo de su carrera en este ámbito de estudio*. Existe, relacionado con esto, un cierto debate sobre si la criminología es, por tanto, una disciplina “autónoma” o no, si es una disciplina o es simplemente un campo de estudio en el que confluyen varias otras disciplinas. Hay muchos criminólogos muy notables que piensan que la criminología no tiene el estatus y rango de las disciplinas científico-sociales tradicionales. David Garland (), por ejemplo, nos dice que no, ya que no tiene un objeto teórico propio o métodos de investigación distintivos (en un sentido parecido, ver también Newburn, 2017).

Es por eso por lo que a veces se discute la criminología usando la metáfora del “punto de encuentro” (Downes, 1988) de disciplinas y especialistas formados en otras disciplinas más que como una disciplina propia, una metáfora más comúnmente usada por quienes se graduaron o doctoraron en otras disciplinas como la sociología o la psicología. Así, por ejemplo, David Smith (2013) nos dice que:

> “La criminología no es una llama sagrada defendida por un grupo selecto de seguidores, ni un sistema unitario y coherente de pensamiento. En su mejor versión, es un grupo de personas que usa un conjunto de herramientas para pensar sobre el delito y sus implicaciones prácticas y teóricas y para testear sus ideas usan la evidencia científica. Su propósito es informar la toma de decisiones políticas y morales. En este sentido, la criminología no es una disciplina académica, sino un ámbito o campo de estudio y los criminólogos tienen una caja llena con las herramientas procedentes de muchas profesiones: la historia, la sociología, la psicología, la psiquiatría, la filosofía del derecho, etc.” (Smith, 2013: 4).

Mientras tanto hay quien, sobre todo quienes tienen su identidad profesional o académica más ligada a la criminología que, en vez de esta metáfora del “punto de encuentro”, ligan la criminología al concepto más técnico de **ciencia interdisciplinar**. Es decir, reconocen que es un proyecto que se nutre de las aportaciones de otras ciencias sociales y que necesita estar interconectada con ellas, pero admiten que no hay que temer designarla, dado el grado de madurez institucional que ha alcanzado, como una disciplina en sentido propio.

¿Qué pensamos nosotros? En España esta no es una cuestión baladí porque vivimos en un país donde la ley y el procedimiento administrativo encorseta en gran medida la práctica social en mayor grado que en otras sociedades. La definición o no de la criminología como una disciplina (lo que en España en terminología administrativa tradicional se conoce como “áreas de conocimiento” y en desarrollos legales recientes como “especialidades científicas”) tiene consecuencias legales importantes para el desarrollo de carreras académicas y la estructuración de la docencia universitaria. Por tanto, no tenemos el lujo, a diferencia de lo que ocurre fuera de nuestras fronteras, de andarnos con matices. Por cuestiones pragmáticas y legales en España no nos queda más remedio que defender la autonomía de la criminología como una especialidad científica si queremos tener un derecho a existir como investigadores en este ámbito. Para nosotros, no cabe duda de que este un campo de estudio con un grado de institucionalización como el que existe en otras áreas de conocimiento (lo vimos anteriormente) y que, en ese sentido, merece tener el mismo grado de reconocimiento oficial que otras disciplinas, como el derecho penal, la psicología social, o la econometría, por poner unos ejemplos.

En España, no obstante, aún no es así: no existen departamentos universitarios de criminología, ni existe un “área de conocimiento” o “especialidad científica” en criminología, por más que las criminólogas españolas llevan luchando por ello con las autoridades educativas durante las últimas décadas. En el marco internacional, como hemos dicho, sí que tenemos departamentos de criminología, y (no solo en España) también existen sociedades científicas, revistas especializadas, titulaciones oficiales, congresos científicos y muchos otros elementos de institucionalización que de alguna manera reconocen que este es un campo de estudio maduro: con un cuerpo teórico que nos puede gustar más o menos, y nos puede parecer más o menos original pero que es centenario y que es necesario conocer si se practica la criminología; y con algunas particularidades en el uso de la metodología propia de las ciencias sociales que uno tiene que conocer bien para poder participar de forma informada en sus debates. En este sentido, como campo de estudio merecedor de un reconocimiento oficial es posible defender, en nuestra opinión, que la criminología es una disciplina “autónoma”, relevante, e interesante. Pero lo importante que tenéis que aprender es que esta es una cuestión bastante debatida fuera de nuestras fronteras, por más que en España no nos quede más remedio que tomar una posición más clara para reivindicarnos y poder practicar la criminología con un mínimo de recursos y posibilidades de desarrollo profesional.

En todo caso, no nos cabe duda de que, y aquí lleva toda la razón David Garland () y otros autores, que ofuscarse con la idea de autonomía puede ser perjudicial y conducir a una insularidad innecesaria que vendría acompañada de un empobrecimiento conceptual, teórico, y metodológico – y que a veces puede llevar a la consolidación de perspectivas teóricas que al ignorar los desarrollos en otros ámbitos científicos pueden ser problemáticas. La interconexión con otras disciplinas, el estar al tanto de desarrollos teóricos y metodológicos en las mismas, y el tener titulaciones universitarias multidisciplinares son necesarios incluso si uno piensa que la criminología es una disciplina “autónoma”. No deberíamos perder esa conexión con las disciplinas básicas en las que se formaron los padres (y madres) de la criminología o nos arriesgamos a “estrechar nuestro horizonte intelectual, a aislarnos de debates e ideas centrales en las ciencias sociales y políticas, o generar trabajos carentes de ambición y amplio interés académico” (Loader y Sparks, 11). Ellos también apuntan a un peligro adicional de la ofuscación con la autonomía.. Si nos empeñamos en destacar nuestra desconexión de las ciencias sociales corremos el peligro de que la investigación criminológica y las titulaciones en este ámbito se hagan:

> “más vulnerables a las influencias externas y los controlen de forma que orienten al campo hacia la resolución de problemas impuestos políticamente y nos aleja de la generación de problemas inspirados por la curiosidad… bajo esas condiciones la relevancia hacia políticas de la criminología podría parecer que quedaría reconocida, pero su papel y funciones cívicas podría atenuarse y oscurecerse”.

Resumiendo, ambas posturas (la criminología como disciplina versus la criminología como campo de estudio y punto de encuentro de otras disciplinas) son opiniones respetables y personalmente creo que con lo que hay que quedarse, por encima de todo, es con la idea de la necesaria interconexión íntima y profunda que la criminología precisa con otras ciencias sociales. Es imposible que un criminólogo sea un experto en todas las disciplinas sociales de las que se nutre la criminología y, en ese sentido, el hacer criminología desde otras disciplinas puede ser particularmente ventajoso en según qué circunstancia porque puedes traer a tus investigaciones un conocimiento más especializado en otra disciplina. Pero en otros contextos, el tener un pie en el patio trasero de muchas otras disciplinas (como debería ocurrir a los graduados en criminología) también puede ser una ventaja competitiva a la hora de estudiar el delito. Ambas son formas legítimas de formarse y practicar la criminología, con sus ventajas y desventajas. En ciencia social lo normal, de cualquier forma, es trabajar en equipo y cualquier carencia que puede tener un investigador a nivel personal se puede compensar teniendo equipos con integrantes que compensen estas carencias.

::: {.callout-note appearance="\"simple"}
**Departamentos de Derecho Penal y Criminología**

En nuestra propuesta de definición también destacamos que es una perspectiva entroncada en las ciencias sociales. Los criminólogos usamos teorías, conceptos, y herramientas metodológicas procedentes de, o muy influenciadas por, otras ciencias sociales. Históricamente surge en el contexto de la filosofía del derecho penal. Posteriormente, durante el siglo XIX, el protagonismo pasa al campo de la psiquiatría, la psicología (inicialmente de la personalidad y diferencial, posteriormente con un mayor peso de la psicología del aprendizaje, la psicología evolutiva, y social), y la sociología, y en las últimas décadas vemos una mayor contribución desde la economía, la geografía, la ciencia política, la antropología, y la historia, entre otras. Al hablar el mismo lenguaje y el usar herramientas similares al de otras ciencias sociales facilita la comunicación y el encuentro de puntos en común con las mismas. Se diferencia así de la ciencia del derecho o jurisprudencia, que fundamentalmente está interesada en el estudio y análisis del ordenamiento jurídico para buscar su adecuada aplicación. ¿Siendo esto así porque los grados de criminología españoles tienen su sede en Facultades de Derecho? La ubicación de los grados e institutos de criminología en Facultades de Derecho que observamos en España, y en algún otro país europeo, es en gran medida un accidente histórico. En aquellos países en los que la criminología cuenta con un mayor respaldo institucional y consolidación social (Estados Unidos, Reino Unido, Países Bajos, etc.) la misma suele ubicarse de forma más clara en las Facultades de Ciencias Sociales. Aunque la criminología española no habría conseguido el reconocimiento institucional que tiene hoy sin el apoyo de visionarios catedráticos de derecho penal que decidieron apostar por la misma, también es cierto que la ubicación de la criminología en Facultades de Derecho en la actualidad condiciona y limita el grado de desarrollo de esta especialidad científica y hace que en los grados se incluyan demasiadas asignaturas con contenidos jurídicos que pueden lastrar la formación de los estudiantes de estos grados. Es evidente que, desde las sociedades científicas, los colegios profesionales, y las asociaciones de alumnos de criminología tenemos que luchar por una reforma de estos planes de estudio y porque se creen departamentos universitarios de criminología.
:::

### Los objetos de la criminología

La criminología se ha venido a ocupar del estudio de la delincuencia y las respuestas a la misma desde sus origenes. Distintas perspectivas teóricas o líneas de investigación han puesto el acento en uno u otro de estos elementos a lo largo de la historia. En la segunda parte de este volumen entraremos a analizar en detalle cada uno de los elementos que han sido objeto de estudio de la criminología. Por tanto, aquí tan solo los enumeraremos de forma muy sintética:

* **El delito**. Las acciones u omisiones merecedoras de algún tipo de reproche social y legal, generalmente penal, y que se escenifan como evento en unas coordenadas espacio temporales concretas.

* **Los delincuentes**. Las personas (naturales o jurídicas) que cometen delitos, sus características, motivaciones y el contexto en el que operan.

* **Las víctimas**. Las personas que son los sujetos pasivos del delito, las consecuencias que el delito tiene para ellas, sus respuestas, y los diferentes mecanismos que la sociedad ha articulado para tratar de dar respuesta a su victimación.

* **Las respuestas estatales al delito**. Fundamentalmente, los procesos de criminalización de determinados comportamientos merecedores de reproche social, el funcionamiento de las instituciones encargadas de dar respuesta a las mismas, etc.

**Las respuestas sociales o culturales al delito**. El delito no solamente da lugar a respuestas estatales, sino que la sociedad en general reacciona al mismo o trata de controlarlo a traves de mecanismos sociales generalmente de naturaleza informal. El delito tambien ha dado lugar a distintas manifestaciones culturales y estas también son de interés para las criminólogas.

### Los sesgos de la criminología



### Criminología y política

## La criminología en España

[^1]: Es un contexto en el que como indican estos autores: "the politicized policy environment has intensified the longstanding tendency of government to directly and indirectly support research with short time horizons that answer pressing policy concerns, while also giving rise to micro-management of the research process and heightened wariness about potentially scandal-creating findings. Some who have been scarred by this new climate have used their experience to expose government’s claim to be doing evidence-based policy as a fiction and to call for a boycott of official research conducted under these conditions (Hope and Walters 2008). Those on the other side of the commissioning fence routinely claim that criminology is today lacking in the required skills and appropriate disposition (Wiles 2001). On the other hand, government has increasingly resorted to other— less demanding and risky—knowledge producers, such as consultancy firms, social research companies, and a thriving ‘public opinion’ industry, to supply the information it requires."" `[@Loader_12, p.]