# Preliminares {.unnumbered}

## Coordinadores y autores

* Juanjo Medina y Lorea Arenas (Coordinadores)

* Juanjo Medina, Lorea Arenas, Jonathan Torres, Raquel Bartolomé, Elisa García España (Autores)

## Plan de trabajo

El plan es intentar tener borradores preliminares del capítulo sobre concepto, delincuentes, delito, respuestas estatales, clase social, y política antes de finalizar el 2025.

Nuestra aspiración es tener la mayor parte del volumen terminado en septiembre del 2026, listo para ser usado en el primer semestre del curso 2026/2027, aunque es posible que algún capítulo se retrase hasta finales del 2026.

Estamos en proceso de garantizar el uso de todas las imágenes empleadas. Algunas de ellas no presentan problemas, para el uso legítimo de otras aún estamos en fase de tramitar los permisos necesarios.

## Convenciones

A lo largo del texto se incluiran citas de trabajos originales en numerosas ocasiones de textos escritos en inglés. Para facilitar la lectura y comprensión estas citas, cuando se inserten en el texto principal, serán traducidas al castellano por los autores del volumen.
